---
language: ruby
bundler_args: --without system_tests
install: ["travis_retry ./.travis.sh"]
script: ["bundle exec rake validate", "bundle exec rake lint", "AUGEAS_LENS_LIB=lib/augeas/lenses bundle exec fakeroot rake spec SPEC_OPTS='--format documentation'", "bundle exec rake metadata"]
matrix:
  fast_finish: true
  include:
  - rvm: 1.8.7
    env: PUPPET_GEM_VERSION="~> 3.0" FACTER_GEM_VERSION="~> 1.7.0"
  - rvm: 1.9.3
    env: PUPPET_GEM_VERSION="~> 3.0"
  - rvm: 2.0.0
    env: PUPPET_GEM_VERSION="~> 3.0"
  - rvm: 2.0.0
    env: PUPPET_GEM_VERSION="~> 3.0" FUTURE_PARSER="yes"
  - rvm: 2.1.0
    env: PUPPET_GEM_VERSION="~> 4.0"
notifications:
  email: false
deploy:
  provider: puppetforge
  user: camptocamp
  password:
    secure: "IT9zyEJdRra47vCzqpKmjbp9Y/mewvvMcE8+8LYm8VZXSAfgL0M1FLizyTstra30Bb7R6dnfIp0VIedo9h21YDXNtbT8dojh1pz9hXvK6Dh8oMqVdl2MkA/55GEty65n2e0OZVfr7Y7lesyAVc2aMUdc/GkJ6uhDvt5XGIHQRS8="
  on:
    tags: true
    # all_branches is required to use tags
    all_branches: true
    # Only publish if our main Ruby target builds
    rvm: 1.9.3
